FROM python:3.10.9

COPY pyproject.toml poetry.lock /app/
WORKDIR /app
RUN pip install poetry && \
    poetry install --no-root
COPY . /app
RUN pip install -r /app/requirements.txt

CMD ["poetry", "run", "celery", "--app", "services.periodic.main:app", "worker", "--beat", "--loglevel=debug"]
