# Generated by Django 4.2.1 on 2023-05-24 15:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bbsh_api", "0005_orderlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basket",
            name="cost",
        ),
        migrations.RemoveField(
            model_name="basket",
            name="size",
        ),
    ]
