# Generated by Django 4.2.1 on 2023-05-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bbsh_api", "0006_remove_basket_cost_remove_basket_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="basket",
            name="size",
            field=models.TextField(blank=True),
        ),
    ]
