# Generated by Django 4.2.1 on 2023-05-24 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bbsh_api", "0008_alter_history_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basket",
            name="name",
        ),
        migrations.RemoveField(
            model_name="basket",
            name="size",
        ),
        migrations.RemoveField(
            model_name="orderlist",
            name="cost",
        ),
        migrations.RemoveField(
            model_name="orderlist",
            name="name",
        ),
        migrations.RemoveField(
            model_name="orderlist",
            name="size",
        ),
        migrations.AddField(
            model_name="basket",
            name="dish",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bbsh_api.menu",
            ),
        ),
        migrations.AddField(
            model_name="orderlist",
            name="dish",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bbsh_api.menu",
            ),
        ),
    ]
