# Generated by Django 4.2.1 on 2023-05-25 16:45

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bbsh_api", "0011_alter_basket_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderlist",
            name="order_id",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name="basket",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="orderlist",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
