# Generated by Django 4.2.1 on 2023-06-07 15:50

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bbsh_api", "0013_alter_orderlist_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
