# Generated by Django 4.2.1 on 2023-06-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bbsh_api", "0014_alter_myuser_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="comments",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="history",
            name="points",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="orderlist",
            name="comments",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="orderlist",
            name="points",
            field=models.IntegerField(default=0),
        ),
    ]
