# Generated by Django 4.2.1 on 2023-06-10 09:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "bbsh_api",
            "0015_history_comments_history_points_orderlist_comments_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="history",
            name="points",
        ),
        migrations.RemoveField(
            model_name="myuser",
            name="points",
        ),
        migrations.RemoveField(
            model_name="orderlist",
            name="points",
        ),
    ]
